node('docker') {
  checkout scm
  dir('tf') {
    stage 'Initialize Terraform'
    sh 'terraform remote config -backend=consul -backend-config="address=consul0:80" -backend-config="path=tf"'
    
    stage 'terraform plan'
    sh 'echo 0 > .tfexit'
    sh 'terraform plan -detailed-exitcode || echo $? > .tfexit'

    if(changes()) {
      stage 'terraform apply'
      input message: "Terraform changes detected.", ok: "Approve changes." 
      sh 'terraform apply'
    }
  }
}

def changes() {
  def matcher = readFile('.tfexit') =~ '^2$'
  matcher ? matcher[0] : null
}
